### ISSUE TITLE
Cerebro plot fails when running in Jupiter notebook

### ISSUE THREAD

**Issue by vladisld** [backtrader2/backtrader#14] opened 2020-06-01 16:47 UTC
**Link to the forum:**  

https://community.backtrader.com/topic/1488/cerebro-plot-failed-to-run

**StackTrace of the error:** 

><IPython.core.display.HTML object>
cerebro.plot()
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\backtrader\cerebro.py", line 996, in plot
plotter.show()
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\backtrader\plot\plot.py", line 794, in show
self.mpyplot.show()
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\matplotlib\pyplot.py", line 254, in show
return _show(*args, **kw)
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\matplotlib\backends\backend_nbagg.py", line 255, in show
manager.show()
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\matplotlib\backends\backend_nbagg.py", line 91, in show
self._create_comm()
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\matplotlib\backends\backend_nbagg.py", line 123, in _create_comm
self.add_web_socket(comm)
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\matplotlib\backends\backend_webagg_core.py", line 433, in add_web_socket
self.resize(w, h)
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\matplotlib\backends\backend_webagg_core.py", line 419, in resize
size=(w / self.canvas._dpi_ratio, h / self.canvas._dpi_ratio))
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\matplotlib\backends\backend_webagg_core.py", line 490, in _send_event
s.send_json(payload)
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\matplotlib\backends\backend_nbagg.py", line 199, in send_json
self.comm.send({'data': json.dumps(content)})
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\ipykernel\comm\comm.py", line 121, in send
data=data, metadata=metadata, buffers=buffers,
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\ipykernel\comm\comm.py", line 66, in _publish_msg
self.kernel.session.send(self.kernel.iopub_socket, msg_type,
AttributeError: 'NoneType' object has no attribute 'session'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\matplotlib_pylab_helpers.py", line 74, in destroy_all
manager.destroy()
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\matplotlib\backends\backend_nbagg.py", line 127, in destroy
self._send_event('close')
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\matplotlib\backends\backend_webagg_core.py", line 490, in _send_event
s.send_json(payload)
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\matplotlib\backends\backend_nbagg.py", line 199, in send_json
self.comm.send({'data': json.dumps(content)})
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\ipykernel\comm\comm.py", line 121, in send
data=data, metadata=metadata, buffers=buffers,
File "C:\Users~\PycharmProjects\helloworld\venv\lib\site-packages\ipykernel\comm\comm.py", line 66, in _publish_msg
self.kernel.session.send(self.kernel.iopub_socket, msg_type,
AttributeError: 'NoneType' object has no attribute 'session'

**Sample code**:

```python
from future import (absolute_import, division, print_function, unicode_literals)
import backtrader as bt

class TestStrategy(bt.Strategy):
    def log(self, txt, dt=None):
        ''' Logging function fot this strategy'''
        dt = dt or self.datas[0].datetime.date(0)
        print('%s, %s' % (dt.isoformat(), txt))

    def __init__(self):
        # Keep a reference to the "close" line in the data[0] dataseries
        self.dataclose = self.datas[0].close

        # To keep track of pending orders and buy price/commission
        self.order = None
        self.buyprice = None
        self.buycomm = None

    def notify_order(self, order):
        if order.status in [order.Submitted, order.Accepted]:
            # Buy/Sell order submitted/accepted to/by broker - Nothing to do
            return

        # Check if an order has been completed
        # Attention: broker could reject order if not enough cash
        if order.status in [order.Completed]:
            if order.isbuy():
                self.log(
                    'BUY EXECUTED, Price: %.2f, Cost: %.2f, Comm %.2f' %
                    (order.executed.price,
                     order.executed.value,
                     order.executed.comm))

                self.buyprice = order.executed.price
                self.buycomm = order.executed.comm
            else:  # Sell
                self.log('SELL EXECUTED, Price: %.2f, Cost: %.2f, Comm %.2f' %
                         (order.executed.price,
                          order.executed.value,
                          order.executed.comm))

            self.bar_executed = len(self)

        elif order.status in [order.Canceled, order.Margin, order.Rejected]:
            self.log('Order Canceled/Margin/Rejected')

        self.order = None

    def notify_trade(self, trade):
        if not trade.isclosed:
            return

        self.log('OPERATION PROFIT, GROSS %.2f, NET %.2f' %
                 (trade.pnl, trade.pnlcomm))

    def next(self):
        # Simply log the closing price of the series from the reference
        self.log('Close, %.2f' % self.dataclose[0])

        # Check if an order is pending ... if yes, we cannot send a 2nd one
        if self.order:
            return

        # Check if we are in the market
        if not self.position:
            # Not yet ... we MIGHT BUY if ...
            if self.dataclose[0] < self.dataclose[-1]:
                # current close less than previous close

                if self.dataclose[-1] < self.dataclose[-2]:
                    # previous close less than the previous close

                    # BUY, BUY, BUY!!! (with default parameters)
                    self.log('BUY CREATE, %.2f' % self.dataclose[0])

                    # Keep track of the created order to avoid a 2nd order
                    self.order = self.buy()
        else:
            # Already in the market ... we might sell
            if len(self) >= (self.bar_executed + 5):
                # SELL, SELL, SELL!!! (with all possible default parameters)
                self.log('SELL CREATE, %.2f' % self.dataclose[0])

                # Keep track of the created order to avoid a 2nd order
                self.order = self.sell()

if name == 'main':
    # Create a cerebro entity
    cerebro = bt.Cerebro()

    # Add a strategy
    strats = cerebro.addstrategy(
        TestStrategy)

    kl = abu.ABuSymbolPd.make_kl_df('F', n_folds=int(2))
    kl = kl[['open', 'high', 'low', 'close', 'volume']]
    data = bt.feeds.PandasData(dataname=kl)

    # Add the Data Feed to Cerebro
    cerebro.adddata(data)

    # Set our desired cash start
    cerebro.broker.setcash(1000.0)
    cerebro.broker.set_coc(True)
    # Add a FixedSize sizer according to the stake
    cerebro.addsizer(bt.sizers.FixedSize, stake=10)

    # Set the commission
    cerebro.broker.setcommission(commission=0.0)

    # Print out the starting conditions
    print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())

    # Run over everything
    cerebro.run()

    # Print out the final result
    print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())

    cerebro.plot()
```

**Details:**

While it's true that this error occurs in the guts of matplotlib, it happens because Backtrader is incorrectly assuming it's running inside a Jupyter notebook and therefore configuring matplotlib with an incorrect backend.

The fix is to use cerebro.plot(iplot=False) when not running inside a Jupyter notebook.

See:
https://www.backtrader.com/blog/posts/2016-09-17-notebook-inline/notebook-inline/
and:
https://community.backtrader.com/topic/2106/cerebro-plot-error/4

**Comment by neilsmurphy** [comment] 2020-06-01 21:34
I would like to take a run at this.

**Comment by neilsmurphy** [comment] 2020-06-11 12:26
I'm having a hard time recreating this error. I've used the same code except swapped  out the data to local data which works fine. I also moved the code under 
```
if name == 'main':
```
(also incorrect) into a function: 
```
def run_strat():
```
so that I could call the module from Jupyter. 
I first ran this in notebook using the system interpreter and the plot runs fine. 
I then created a virtual env and did not install matplotlib. I installed backtrader and set up an kernel as: 
```
ipython kernel install --user --name=jupyter_fails
```
The code failed in jupyter without matplotlib. I installed matplotlib in the venv and then tested it in Jupyter, it runs fine. 
To say it runs fine in jupyter, I'm getting the full interactive plot inline. I did not use any magic commands. Here is my code in Jupyter.
```
import jupyter_plot_fails as jpf
jpf.run_strat()
```
![image](https://user-images.githubusercontent.com/41596659/84385022-e4db4c80-abbc-11ea-8e81-3157cb601243.png)

Finally I asked @Joe-Landers [here](https://community.backtrader.com/topic/1488/cerebro-plot-failed-to-run/6) for help re-creating the problem and I'm still waiting for an answer.

Any assistance to help me re-create this issue would be appreciated.

**Comment by neilsmurphy** [comment] 2020-06-13 22:59
I asked for further information from the [poster](https://community.backtrader.com/topic/1488/cerebro-plot-failed-to-run/7) of the matplotlib issue in Jupyter, it appears the problem is externally generated as best I can tell. 

> Yes, I found that using cerebro.plot(iplot=False) when not running in a notebook worked. Also, this is only needed (for me at least) if the Jupyter server happens to be running (even in the background) at the time.
> 
> Interestingly, I had another problem whereby matplotlib plots would crash whenever I scrolled. I Googled around learned it's because I installed Python from Homebrew on my mac, and that version of python doesn't have the same gui toolkit as the "full" version. I uninstalled that version of python and installed the official distribution from python.org and now both problems are gone 
> 
> However, if you're asking whether I found a better way to detect whether or not we're running inside a notebook? No, I didn't. However, I think the better answer is to not auto-detect at all. Most Jupyter users are quite familiar with using the %matplotlib inline majik when plotting in Jupyter. However, this auto-detection foobar is messing that up too.
> 
> Ran into another issues today whereby the plots stopped showing up in my Jupyter notebooks (using just cerebro.plot(). On a hunch, I decided to try cerebro.plot(iplot=False) inside the Jupyter notebook to see what would happen. As long as I have the majick %matplotlib inline somewhere in my notebook, that issue is also fixed.

I'm unable to recreate this issue and the user indicates this problem is external. Unless I'm missing something I'm going to close this issue. 

Please let me know what you think @ab-trader  @vladisld

**Comment by vladisld** [comment] 2020-06-13 23:39
It seems the problem is with Jupyter configuration indeed.  However, I expect this issue will be raised in the future so we may either reference the above community post or consider adding this to the documentation.  

BTW, about the documentation - should we probably fork the documentation repository as well?

**Comment by neilsmurphy** [comment] 2020-06-15 10:58
I'll make a note in the community linking here. 

We should probably for the docs too.

**Closed** 2020-06-15 10:58 UTC
Labels: bug
